export const ASSIGNMENT_NICHE_OPTIONS = [
  "Recruiting firms",
  "Staffing firms",
  "Marketing agencies",
  "Creative agencies",
  "Web design agencies",
  "Small SaaS",
  "SaaS support teams",
  "Consulting firms",
  "Professional services",
  "B2B service companies",
] as const

export const ASSIGNMENT_REGION_OPTIONS = [
  "Global",
  "United States",
  "New York",
  "California",
  "Texas",
  "Florida",
  "Illinois",
  "Washington",
  "Massachusetts",
  "Georgia",
  "North Carolina",
  "Colorado",
  "Virginia",
  "Arizona",
  "Pennsylvania",
  "Ohio",
  "Michigan",
  "New Jersey",
  "Minnesota",
  "Tennessee",
  "Oregon",
  "Utah",
  "San Francisco, CA",
  "Los Angeles, CA",
  "San Diego, CA",
  "New York City, NY",
  "Austin, TX",
  "Dallas, TX",
  "Houston, TX",
  "Miami, FL",
  "Chicago, IL",
  "Seattle, WA",
  "Boston, MA",
  "Atlanta, GA",
  "Denver, CO",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "Washington, DC",
  "Canada",
  "Toronto, ON",
  "Vancouver, BC",
  "Montreal, QC",
  "Calgary, AB",
  "United Kingdom",
  "London",
  "Manchester",
  "Birmingham",
  "Leeds",
  "Edinburgh",
  "Glasgow",
  "Bristol",
  "Liverpool",
  "Europe",
  "Ireland",
  "Dublin",
  "France",
  "Paris",
  "Germany",
  "Berlin",
  "Munich",
  "Hamburg",
  "Netherlands",
  "Amsterdam",
  "Rotterdam",
  "Spain",
  "Madrid",
  "Barcelona",
  "Italy",
  "Milan",
  "Rome",
  "Switzerland",
  "Zurich",
  "Geneva",
  "Belgium",
  "Brussels",
  "Sweden",
  "Stockholm",
  "Denmark",
  "Copenhagen",
  "Norway",
  "Oslo",
  "Finland",
  "Helsinki",
  "Portugal",
  "Lisbon",
  "Poland",
  "Warsaw",
  "Austria",
  "Vienna",
  "Czech Republic",
  "Prague",
  "Nigeria",
  "Lagos",
  "Abuja",
  "Australia",
  "Sydney",
  "Melbourne",
  "Brisbane",
  "Perth",
  "Middle East",
  "United Arab Emirates",
  "Dubai",
  "Abu Dhabi",
] as const
